
export const GET_INGREDINTS = "GET_INGREDINTS";

export const UPDATE_STOCK = "UPDATE_STOCK";

export const CREATE_INGREDINT_REQUEST = "CREATE_INGREDINT_REQUEST";
export const CREATE_INGREDINT_SUCCESS = "CREATE_INGREDINT_SUCCESS";
export const CREATE_INGREDINT_FAILURE = "CREATE_INGREDINT_FAILURE";

export const CREATE_INGREDINT_CATEGORY_REQUEST = "CREATE_INGREDINT_REQUEST";
export const CREATE_INGREDINT_CATEGORY_SUCCESS = "CREATE_INGREDINT_SUCCESS";
export const CREATE_INGREDINT_CATEGORY_FAILURE = "CREATE_INGREDINT_FAILURE";

export const GET_INGREDINT_CATEGORY_REQUEST = "GET_INGREDINT_CATEGORY_REQUEST";
export const GET_INGREDINT_CATEGORY_SUCCESS = "GET_INGREDINT_CATEGORY_SUCCESS";
export const GET_INGREDINT_CATEGORY_FAILURE = "GET_INGREDINT_CATEGORY_FAILURE";